[package]
name = "sbpg"
version = "0.1.0"
authors = ["Kybox - Yann <nslr@riseup.net>"]
edition = "2018"

[dependencies]
dirs = "1.0"
regex = "1"
include_dir = "0.2.1"
colored = "1.8"
winapi = "0.3.7"
dialoguer = "0.4.0"

[dependencies.Inflector]
version = "*"
default-features = false
